#!/bin/bash
clear

read -p "masukkan kode regestrasi anda : " coders;
case $coders in


arc078)

clear

pkg install git

clear

echo "ARC_store v6.0i"
echo " "
    echo "+ [update]::::::::::::::::ARC_store//"
    echo "[p1]+ ip checker "
    echo "[p2]+ disk cleaner "
    echo "[p3]+ website hacker "
    echo "[p4]+ wifi hacker(root)"
    echo " "

read -p "install nomor :" aninput
case $aninput in


p1)

  clear
  echo "installing"
  git clone https://github.com/afri64/ipchecker/
  cd
  cd ipchecker
  bash ipchk

;;

p2)

 clear
  echo "installing..."
  cd 
  git clone https://github.com/afri64/disk/
  cd
  cd disk 
  bash dsc

;;

p3)

  clear
  echo "installing"
  cd
  git clone https://github.com/afri64/arcsite
  cd 
  cd arcsite
  bash awb

;;

p4)

 clear
 echo "installing"
 cd
 git clone https://github.com/afri64/arcwifi
 cd
 cd arcwifi
 clear
 echo "3 tab harus dibuka manual"
 
;;

update)



  clear
  echo "updating..."
  cd 
  rm -r devstore
  git clone https://github.com/afri64/devstore/
  cd
  cd devstore
  bash store


;;

*)

 clear
 echo "[!]massukan pilihan yang valid]"

;;

esac
esac